### ISSUE TITLE
com.bumptech.glide.RequestManager

### ISSUE THREAD

**Issue by banli17** [reactnativecomponent/react-native-imui#14]
java.lang.NoSuchMethodError: No virtual method load(Ljava/io/File;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/xxxx2/base.apk:classes2.dex)
 at cn.jiguang.imui.messagelist.ReactMsgListManager$4.loadImage(ReactMsgListManager.java:237)
 at

**Comment by hyhing** [comment]
请问你解决了吗 @banli17

**Comment by hzlgit** [comment]
未发现该问题，我更新了版本，如有问题可以另开issues详细描述问题
