### ISSUE TITLE
你的这ui框架有个BUG,就是点击输入表情的时候再点击下就可以看到问题的所在了。

### ISSUE THREAD

**Issue by garyhu1** [reactnativecomponent/react-native-imui#4]

**Comment by hzlgit** [comment]
@garyhu1 请描述的详细一些。最好有截图

**Comment by garyhu1** [comment]
我刚打开聊天页面，首先点击表情，弹出表情框，表情图片改变为了键盘图片，接着再点击键盘图片，输入法出现，遮盖了输入框，而且键盘图片也不会变为表情图片，我看了你的源码设置了在两次点击同一个id按钮时，设置showType = -1,然后调用dismissMenuAndResetSoftMode()方法，这个方法内部的处理是软键盘遮盖输入法的操作。就这里的问题。

**Comment by xhp** [comment]
@garyhu1 遮盖了输入框有没有截图

**Comment by aijason** [comment]
这个问题还是存在呀，切换表情后切回键盘，键盘挡住输入框，输入框收起了。

**Comment by aijason** [comment]
解决了，汗~
