### ISSUE TITLE
appendMessages insertMessagesToTop app 卡死退出

### ISSUE THREAD

**Issue by jys125773** [reactnativecomponent/react-native-imui#6]
调用AuroraIController 的 appendMessages，insertMessagesToTop方法，MessagesList 不能添加消息，并且app卡死，闪退

**Comment by hzlgit** [comment]
请描述详细一点，比如平台、是否集成成功等

**Comment by jys125773** [comment]
集成成功了，Xcode编译通过

平台
MacOS 10.13.3
Xcode 9.2

react-native版本
react: "^16.3.0-alpha.1"
react-native: "0.54.4"

Podfile配置
platform :ios, '8.0'
target 'test' do
  pod 'SDWebImage', '~>4.0.0'
end
我看见你的demo的“React”那一项配置是
 pod "React", :path => "../node_modules/react-native"，:subspecs => [
'BatchedBridge'
]
不知道什么意思，新版本由‘BatchedBridge’变成‘CxxBridge’了

调用

function transformMessage(message) {
  const { messageUId } = message
  return {
    msgId: messageUId,
    status: "send_going",
    msgType: "text",
    isOutgoing: true,
    text: "text",
    fromUser: {
      userId: "user1",
      displayName: "user1",
      avatarPath:""
    },
  }
}

  componentDidMount() {
    setTimeout(() => {
      AuroraIController.appendMessages(
        [1，2，3，4].map((_, i) => transformMessage({ messageUId: i + '' }))
      );

    }, 6000)
  }

一旦调用appendMessages界面就卡死，自动退出，insertMessagesToTop方法也一样。
并且MessagesListView组件的initalData如果传入的不是空数组也是一样的表现

App.js

import React from 'react'
import {
  StyleSheet,
  Dimensions,
  NativeModules,
  Animated,
  View,
  Button,
  Text,
  TextInput
} from 'react-native'
import IMUI from 'react-native-imui'
const AnimatedImplementation = require('react-native/Libraries/Animated/src/AnimatedImplementation')
const AuroraIController = NativeModules.AuroraIMUIModule
const InputView = AnimatedImplementation.createAnimatedComponent(IMUI.ChatInput)
const MessageListView = AnimatedImplementation.createAnimatedComponent(IMUI.MessageList)
const window = Dimensions.get('window')

const conversationType = 1
const targetId = 'test1'

class Chat extends React.Component {
  constructor(props) {
    super(props)

    this.state = {
      isInitialized: false,
      inputViewHeight: new Animated.Value(50),
      inputViewWidth: 0,
      showType: 0,
      menuViewH: 240,
      viewY: 50,
      messages: []
    }

    this._isAutoScroll = true
    this._isListenKeyBoard = true
  }
  componentDidMount() {

    setTimeout(() => {
      AuroraIController.appendMessages(
        [1].map((_, i) => transformMessage({ messageUId: i + '' }))
      );

    }, 6000)
  }

  onChangeBarHeight = (inputHeight, marginTop) => {
    Animated.timing(this.state.inputViewHeight, {
      toValue: inputHeight,
      duration: 310
    }).start()

    this.setState({
      viewY: marginTop,
    })
  }

  onShowKeyboard = (inputHeight, showType) => {
    if (this._isListenKeyBoard) {
      Animated.timing(this.state.inputViewHeight, {
        toValue: inputHeight,
        duration: 310
      }).start()
      this.setState({
        showType: showType,
      })
    }
  }

  onBeginDragMessageList = () => {
    AuroraIController.hidenFeatureView(true)
  }

  onSendTextMessage = (text, IDArr) => {
    console.log(text, IDArr);
  }

  onSendRecordMessage = (path) => {
    console.log(path, '0');
  }

  onFeatureView = (inputHeight, showType) => {
    Animated.timing(this.state.inputViewHeight, {
      toValue: inputHeight,
      duration: 310
    }).start()
    this.setState({
      showType: showType,
    })
  }

  onClickChangeAutoScroll = (isAutoScroll) => {
    this._isAutoScroll = isAutoScroll
  }

  renderCustomContent() {
    if (this.state.showType === 0) {//不显示
      return null
    } else if (this.state.showType === 1) {//显示菜单
      return (
        <View style={{
          height: this.state.menuViewH, width: window.width,
          marginTop: this.state.viewY, flexGrow: 1, backgroundColor: "white"
        }}>
          <View style={{ height: 1, backgroundColor: "#EAEAEA" }} />
          <Text>12345</Text>
          <TextInput value="1234"></TextInput>
        </View>
      )
    }
  }

  onViewLayout = (e) => {
    const layout = e.nativeEvent.layout
    if (layout.height === 0) {
      return
    }
    this.setState({
      isInitialized: true,
      inputViewHeight: new Animated.Value(50),
      inputViewWidth: window.width,
    })
  }

  render() {
    if (!this.state.isInitialized) {
      return <View style={styles.container} onLayout={this.onViewLayout} />
    }

    return (
      <View style={styles.container}>
        <MessageListView
          style={[styles.messageList]}
          initalData={[]}
          onAvatarClick={() => { }}
          onMsgClick={() => { }}
          onMsgOpenUrlClick={() => { }}
          onDealWithMenuClick={() => { }}
          onStatusViewClick={() => { }}
          onTapMessageCell={(v) => {
            console.log(v)
          }}
          onClickChangeAutoScroll={this.onClickChangeAutoScroll}
          onBeginDragMessageList={this.onBeginDragMessageList}
          onClickLoadMessages={() => { }}
          avatarSize={{ width: 40, height: 40 }}
          sendBubbleTextSize={18}
          sendBubbleTextColor={"000000"} />
        <InputView
          style={{ width: this.state.inputViewWidth, height: this.state.inputViewHeight }}
          menuViewH={this.state.menuViewH}
          defaultToolHeight={50}
          onFeatureView={this.onFeatureView}
          onShowKeyboard={this.onShowKeyboard}
          onChangeBarHeight={this.onChangeBarHeight}
          onSendTextMessage={this.onSendTextMessage}
          onSendRecordMessage={this.onSendRecordMessage}
          onClickMention={(v) => {
            console.log('onClickMention')
          }}>
          {this.renderCustomContent()}
        </InputView>
      </View>
    )
  }
}

export default Chat

const { width, height } = Dimensions.get('window')
const sWidth = width - 55 * 4
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5FCFF',
  },
  messageList: {
    flex: 1,
    marginTop: 0,
    width: window.width,
    margin: 0,
  },
  inputView: {
    backgroundColor: 'green',
    width: window.width,
    height: 100,

  },
})

export function transformMessage(message) {
  const { messageUId } = message

  return {
    msgId: messageUId,
    status: "send_going",
    msgType: "text",
    isOutgoing: true,
    text: "text",
    fromUser: {
      userId: "user1",
      displayName: "user1",
      avatarPath:""
    },
  }
}

**Comment by jys125773** [comment]
我发现ios要把消息格式加上“timeString”，“timeStamp”两个属性才可以
{
          msgId: 'wqwwq',
          status: "send_going",
          msgType: "text",
          isOutgoing: false,
          text: "text",
          timeString: Date.now() + '',
          timeStamp: Date.now() + '',
          isShowTime:false,
          fromUser: {
            userId: 'ddd',
            // '_id': "user1",
            displayName: "user1",
            avatarPath: ""
          }

安卓
 isOutgoing传布尔值报错
fromUser是这样的格式
 fromUser: {
            '_id': "user1",
            name: "user1",
            avatar: ""
   }

**Comment by hzlgit** [comment]
@jys125773 这个库是根据im那个库的数据来的，具体数据结构可以看demo的。
