### ISSUE TITLE
能够给出自定义消息操作的步骤

### ISSUE THREAD

**Issue by cesar-blog** [reactnativecomponent/react-native-imui#7]
RT
jpush ui已经支持自定义消息，云信UI是否能更进，或者给出自定义UI的操作步骤，谢谢！！

**Comment by OMysVison** [comment]
已参考jpush ui实现了支持自定义消息类型，但感觉实用性不是很强。

**Comment by OMysVison** [comment]
@cesar-blog 已参考jpush ui实现了支持自定义消息类型，但感觉实用性不是很强。
