### ISSUE TITLE
iOS 第一次弹出录音权限授权，拒绝后可能导致崩溃

### ISSUE THREAD

**Issue by EvianZhow** [reactnativecomponent/react-native-imui#8]
在 RCTAuroraIMUI 项目中的 `DWRecordButton.m` 中，[Line 193](https://github.com/reactnativecomponent/react-native-imui/blob/9d9babfb7cf5632fff65da3216c20f9febc6005c/ios/RCTAuroraIMUI/DWCustomView/InputView/DWRecordButton.m#L193) `- (BOOL)getVoiceAVAuthorizationStatus` 中崩溃。

原因是 RCTAuroraIMUI 项目导出的 Manager 未指定运行的 `<RCTBridgeModule>` 协议中的 `methodQueue`，第一次弹出授权时可能会因为执行队列非 Main Thread、用户拒绝操作回调了 UIKit 的 UIAlertView 的 show 方法导致崩溃。

**Comment by OMysVison** [comment]
已修复
